### ISSUE TITLE
Stack trace disclosure in /api/v1/shorten

### ISSUE THREAD

**Issue by benjammin4dayz** [benjammin4dayz/shortlink#1]
It is possible to expose the underlying file structure of the host system by sending a POST request with a non-JSON payload to `/api/v1/shorten`. Although all errors are caught, the full stack trace is returned in the response as `text/html`.

This appears to be intended behavior and it happens because no other middleware is handling the error. [^1]

**Steps to Reproduce**

```js
await fetch('/api/v1/shorten', {
  method: 'POST',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  body: 'not json',
}).then(res => res.text());
```

```js
SyntaxError: Unexpected token 'n', "not json" is not valid JSON
 at JSON.parse (<anonymous>)
 at createStrictSyntaxError (app/node_modules/body-parser/lib/types/json.js:169:10)
 at parse (app/node_modules/body-parser/lib/types/json.js:86:15)
 at app/node_modules/body-parser/lib/read.js:128:18
 at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
 at invokeCallback (app/node_modules/raw-body/index.js:238:16)
 at done (app/node_modules/raw-body/index.js:227:7)
 at IncomingMessage.onEnd (app/node_modules/raw-body/index.js:287:7)
 at IncomingMessage.emit (node:events:519:28)
 at IncomingMessage.emit (node:domain:488:12)
 at endReadableNT (node:internal/streams/readable:1696:12)
 at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Discovered by @xisz

[^1]: https://stackoverflow.com/questions/58134287/catch-error-for-bad-json-format-thrown-by-express-json-middleware

**Comment by benjammin4dayz** [comment]
Resolved in v0.1.1 @ 720f823

Instead of returning `text/html` with the stack trace data, the response will now include `application/json` with a status code and message about the error.

![image](https://github.com/user-attachments/assets/803509c0-1310-4c91-ae17-10e8de616b16)
